### ISSUE TITLE
您好，想问下您的硬件加速怎么弄的

### ISSUE THREAD

**Issue by hrtan99** [leonhom/GA-B75-D3H-Catalina-EFI#1]
我的配置和你差不多，是e3 1231 v3 b85m-e45 r9-280x
我这边没法开启硬件加速

**Comment by leonhom** [comment]
配置不一样，驱动也不太一样；我的硬件加速在安装完成后就可以使用了；不过驱动也是东拼西凑搞了一段时间才搞定的。

**Comment by leonhom** [comment]
> 配置不一样，驱动也不太一样；我的硬件加速在安装完成后就可以使用了；不过驱动也是东拼西凑搞了该才搞定的。

111

**Comment by leonhom** [comment]
> 我的配置和你差不多，是e3 1231 v3 b85m-e45 r9-280x
> 我这边没法开启硬件加速

配置不一样，驱动也不太一样；我的硬件加速在安装完成后就可以使用了；不过驱动也是东拼西凑搞了一段时间才搞定的。

**Comment by hrtan99** [comment]
> > 我的配置和你差不多，是e3 1231 v3 b85m-e45 r9-280x
> > 我这边没法开启硬件加速
> 
> 配置不一样，驱动也不太一样；我的硬件加速在安装完成后就可以使用了；不过驱动也是东拼西凑搞了一段时间才搞定的。

好的，我再另外找找

**Comment by leonhom** [comment]
> > > 我的配置和你差不多，是e3 1231 v3 b85m-e45 r9-280x
> > > 我这边没法开启硬件加速
> > 
> > 
> > 配置不一样，驱动也不太一样；我的硬件加速在安装完成后就可以使用了；不过驱动也是东拼西凑搞了一段时间才搞定的。
> 
> 好的，我再另外找找

之前不知道在哪儿看到过，没有核显，编码无解的，除非Vega；我也没验证过，平时对这个也没什么需求；你这个估计也是一样，刚论坛搂了一圈，你参考看看
http://bbs.pcbeta.com/viewthread-1805149-1-1.html
http://bbs.pcbeta.com/forum.php?mod=viewthread&tid=1797602&ordertype=2
https://www.jianshu.com/p/7112ae42db98
https://www.tonymacx86.com/threads/radeon-rx-4xx-5xx-standalone-system-amdradeonx4250-kext-gva-support-h264-does-not-support-hevc-hw.240353/

**Comment by zhifu1996** [comment]
处理器(CPU) | 英特尔 Xeon(至强) E3-1230 V2 @ 3.30GHz 四核 |   |  
-- | -- | -- | --
主 板 | 微星 B75A-G41 (MS-7758) |   |  
内 存 | 16 GB ( 威刚 DDR3 1600MHz / 金士顿 DDR3 1333MHz ) |   |  
硬 盘 | 东芝 THNSNJ128GCSU ( 128 GB / 固态硬盘 ) |   |  
显 卡 | AMD Radeon HD 7800 Series ( 1 GB / 蓝宝石 ) |   |  
显示器 | 中强 CTX530D CTX E24K5GDVI ( 31.5 英寸 )

我这个配置可以装吗

**Comment by leonhom** [comment]
> 处理器(CPU)	英特尔 Xeon(至强) E3-1230 V2 @ 3.30GHz 四核	 	 
> 主 板	微星 B75A-G41 (MS-7758)	 	 
> 内 存	16 GB ( 威刚 DDR3 1600MHz / 金士顿 DDR3 1333MHz )	 	 
> 硬 盘	东芝 THNSNJ128GCSU ( 128 GB / 固态硬盘 )	 	 
> 显 卡	AMD Radeon HD 7800 Series ( 1 GB / 蓝宝石 )	 	 
> 显示器	中强 CTX530D CTX E24K5GDVI ( 31.5 英寸 )		
> 我这个配置可以装吗

可以装的，不过主要和显卡的驱动可能要自己找下适配一下
